apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  replicas: 2
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: us-central1-docker.pkg.dev/monitor-426815/monitor-app/monitor:v2
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
spec:
  selector:
    app: monitor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
